name: Frank LSF

baseurl: /prehistory

plugins:
  - jekyll-coffeescript

exclude:
  - deploy.sh
  - franklsf.org.sublime-project
  - Gemfile
  - Gemfile.lock
  - Guardfile
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

coffee:
  style: :compressed
