name: Frank LSF
exclude:
 - deploy.sh
 - franklsf.org.sublime-project
 - Gemfile
 - Gemfile.lock
 - Guardfile
 - README.md

sass:
    sass_dir: _sass
    style: :compressed
coffee:
    style: :compressed
